# Generated by Django 4.2 on 2023-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
