# Generated by Django 4.2 on 2023-04-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
