# Generated by Django 4.2 on 2023-04-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_comment_postcomment_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay', to='core.post'),
        ),
    ]
