# Generated by Django 4.2 on 2023-04-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_replay_post_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
