# Generated by Django 4.2 on 2023-04-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.postlike'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.post'),
        ),
    ]
